# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
#            # 主库数据源 张超服务器
#            master:
#                url: jdbc:mysql://47.94.238.110:3306/ry2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#                username: root
#                password: Qwer1234!@#$
#            # （目前只读）思信数据源 - 应急广播 - broad
#            slave:
#                enabled: true
#                url: jdbc:mysql://110.53.162.164:3306/broad?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#                username: root
#                password: sx123456Aa
#            # 思信数据源 - 应急广播 - user
#            sxuser:
#                enabled: true
#                url: jdbc:mysql://110.53.162.164:3306/user?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#                username: root
#                password: sx123456Aa
#            # 思信数据源 - 物联网系统
#            sxinfom:
#                enabled: true
#                url: jdbc:mysql://110.53.162.164:3306/shuofang?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#                username: root
#                password: sx123456Aa
#            # 思信数据源 - 山洪预警 - rivervis
#            sxrivervis:
#                enabled: true
#                url: jdbc:mysql://110.53.162.164:3306/rivervis?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#                username: root
#                password: sx123456Aa
#            # 思信数据源 - 村务管理 - village
#            sxvillage:
#                enabled: true
#                url: jdbc:mysql://110.53.162.164:3306/village?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#                username: root
#                password: sx123456Aa
#            # 思信数据源 - 村务宝典 - baodian
#            sxbaodian:
#                enabled: true
#                url: jdbc:mysql://110.53.162.164:3306/baodian_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#                username: root
#                password: sx123456Aa

            # 思信服务器
            # 主库数据源 张超服务器
            master:
                url: jdbc:mysql://110.53.162.165:3306/ry?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: sx123456AaBb
            # （目前只读）思信数据源 - 应急广播 - broad
            slave:
                enabled: true
                url: jdbc:mysql://110.53.162.165:3306/broad?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: sx123456AaBb
            # 思信数据源 - 应急广播 - user
            sxuser:
                enabled: true
                url: jdbc:mysql://110.53.162.165:3306/user?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: sx123456AaBb
            # 思信数据源 - 物联网系统
            sxinfom:
                enabled: true
                url: jdbc:mysql://110.53.162.165:3306/shuofang?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: sx123456AaBb
            # 思信数据源 - 山洪预警 - rivervis
            sxrivervis:
                enabled: true
                url: jdbc:mysql://110.53.162.165:3306/rivervis?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: sx123456AaBb
            # 思信数据源 - 村务管理 - village
            sxvillage:
                enabled: true
                url: jdbc:mysql://110.53.162.165:3306/village?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: sx123456AaBb
             # 思信数据源 - 村务宝典 - baodian
            sxbaodian:
                enabled: true
                url: jdbc:mysql://110.53.162.165:3306/baodian_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: sx123456AaBb

            # 初始连接数
            initial-size: 10
            # 最大连接池数量
            max-active: 100
            # 最小连接池数量
            min-idle: 10
            # 配置获取连接等待超时的时间
            max-wait: 60000
            # 打开PSCache，并且指定每个连接上PSCache的大小
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /monitor/druid/*
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true